### ISSUE TITLE
Is it possible to keep widget original width

### ISSUE THREAD

**Issue by fehler001** [TheTechRobo/tkScrolledFrame#1]
When using tkScrolledFrame, widget original width become fixed.  
Is it possible to let widget width remain the same like in official frame, or when user select turning off the Horizontal ScrollBarX.
  
When using tkScrolledFrame  
![1](https://user-images.githubusercontent.com/20217527/126293825-c2344184-5d9b-4296-8a18-c5e8345e7839.JPG)
  
when using ttk official frame  
![2](https://user-images.githubusercontent.com/20217527/126294282-fe3d0abd-36db-472f-a506-e449ee709899.JPG)

**Comment by TheTechRobo** [comment]
Do you mean that the widgets don't resize while in the frame? I'm not quite sure what you're asking.

**Comment by fehler001** [comment]
Yeah, that's what I mean  
In ttk.frame, if I config widget "fill = x", widget will expand or shrinking automatically  
I just want to know is it possible to get same result in tkScrolledFrame

**Comment by TheTechRobo** [comment]
I'm not sure - I didn't write this library.  
Just made a fork so issues and PRs can be made once again.

Wouldn't you be able to do a fill=x in the widget you're putting inside the frame?  
Or does that not work?

**Comment by fehler001** [comment]
That doesn't work, maybe that's why tkinter doesn't officially support scrolled frame.  
But tkinter also doesn't officially support drag and drop, that's quite confused me.
  
OK, I'll close the issue.

**Comment by TheTechRobo** [comment]
Tkinter is really old. That's the main reason.

Have you tried putting the widgets you need in a second frame from your scrolledFrame?

Or did you find a solution?

I'll reopen it for now. I only close questions if they're answered! :P

**Comment by fehler001** [comment]
I tried, it doesn't work.  
  
I'll accept the slight flaw, since this is just a script I made for myself

**Comment by TheTechRobo** [comment]
Damn. I'll try to figure things out.

If you still want to try things, what about a normal frame? Does "fill" parameter work in a normal frame in which case it's an issue with tkScrolledFrame, or is it an issue with the Frame itself? If it's the former, I might be able to fix it; if it's the latter, that's a Tk(inter?) issue.

**Comment by fehler001** [comment]
Sometime, tkinter really drive people crazy.  
like if you .place() a frame inside a .place()ed frame, depending on how "relx, rely" is set, inside frame may or may not show itself.  
Or if you chose to .pack() a frame, inside it, .place() a frame may not work anymore.  
  
I think it a bug of tkinter, you shouldn't waster too much of your time on it, which I already did😂  
  
Just let it go.

**Comment by TheTechRobo** [comment]
Okay, I'll close the issue.

I just don't like leaving questions unanswered :P
